### Prueba de inicio de sesión exitoso
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "juan",
  "password": "password123"
}

### Prueba de inicio de sesión fallido (credenciales incorrectas)
POST http://127.0.0.1:5000/login
Content-Type: application/json

{
  "username": "juan",
  "password": "wrongpassword"
}

### Prueba de acceso a artículos (usuario autenticado)
GET http://127.0.0.1:5000/articulos
Authorization: Bearer <TOKEN_DE_AUTENTICACIÓN>

###

### Prueba de acceso a artículos exclusivos para admin
GET http://127.0.0.1:5000/admin/articulos
Authorization: Bearer <TOKEN_DE_AUTENTICACIÓN>

###

### Prueba de acceso no autorizado
GET http://127.0.0.1:5000/admin/articulos