### Prueba de registro exitoso
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword123",
  "role": "user"
}

### Prueba de registro fallido (falta de datos)
POST http://127.0.0.1:5000/register
Content-Type: application/json

{
  "username": "",
  "password": "short"
}